In [2]:
# Variables and Data Type

# There are 5 main data types in R:
# 1. Numeric  ------> similar to double in python. Takes more space than integer.(6,7,8,4,55 etc..)
# 2. Integer  ------> same to integer. The main difference is that it takes less space than numeric.(4L, 5L, 8L etc..)
# 3. Logical  ------> TRUE or FALSE. Same as boolean.
# 4. Character -----> "Hello". There's no String type in R. All string is also character type.
# 5. Complex  ------> Used to represent complex number where an imaginary 'i' is attached to a real number.

6
typeof(6)
typeof(6L)
typeof(T)
typeof(TRUE)
typeof("Hello")
typeof(4+5i)
TRUE == T

# Type casting
typeof(as.integer(90))
typeof(as.character)

[1] 6

[1] "double"

[1] "integer"

[1] "logical"

[1] "logical"

[1] "character"

[1] "complex"

[1] TRUE

[1] "integer"

[1] "character"

In [19]:
# Combine Multiple Elements
# --> When working with multiple elements of data type, use the function c() to combine multiple elements.

typeof(c(4,6,7))
typeof(c(4L, 80, "Hello"))

# 'c()' --> This is a single dimensional vector. Used to combine multiple elements

# Variables
# --> Variable is a container which stores a value and can change it's value also.

# Ways to assign a variable in R:

x = 444
y <- 66
10 -> p
p
x
y
z <- 1: 10  #This is how we define a sequence in R.
z
z[50]
mode(c(x, y))

# '%%'  --> Modulus(Reminder from division of numbers)
#  '%/%  --> Integer division
#  '/'  --> Division
#  '*'  --> Multiplication
# '%*%' --> Matrix Multiplication (one matrix col number should be equal to another matrix row number)
# '%in%  --> included in

x / y
x %% y
x %/% y
print("-------------------")
mat1 <- matrix(c(2,3,2,6,8,1,5,4,9), ncol = 3, nrow = 3)
mat1
print("-------------------")
mat2 <- matrix(c(1,2,3,4,5,6,7,8,9), ncol = 3, nrow = 3)
mat2
print("-------------------")
mat1 %*% mat2

print(500 %in% z)


sum(z)
mean(z)
summary(z)
is.na(z)
all(z)
any(is.na(z))
any(z)

[1] "double"

[1] "character"

[1] 10

[1] 444

[1] 66

 [1]  1  2  3  4  5  6  7  8  9 10

[1] NA

[1] "numeric"

[1] 6.727273

[1] 48

[1] 6

[1] "-------------------"

     [,1] [,2] [,3]
[1,] 2    6    5
[2,] 3    8    4
[3,] 2    1    9

[1] "-------------------"

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] "-------------------"

     [,1] [,2] [,3]
[1,] 29   68   107
[2,] 31   76   121
[3,] 31   67   103

[1] FALSE

[1] 55

[1] 5.5

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   1.00    3.25    5.50    5.50    7.75   10.00

 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

[1] TRUE

[1] FALSE

[1] TRUE